### ISSUE TITLE
Jobs on Lambda successfully complete the job, but generate CloudWatch error

### ISSUE THREAD

**Issue by diidiiman** [customink/lambdakiq#27]
It seems that that jobs are being run in the same way as HTTP requests and rely on body being returned to the handler, although with jobs (as to my understanding) this should not be required.

Has anyone faced the same issue and have suggestions on how to handle it?

```
Critical exception from handler {
  "errorMessage": "undefined method `each' for nil:NilClass",
  "errorType": "Function<NoMethodError>",
  "stackTrace": [
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby/handler.rb:43:in `block in body'",
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby/handler.rb:42:in `tap'",
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby/handler.rb:42:in `body'",
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby/handler.rb:23:in `response'",
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby/handler.rb:7:in `call'",
    "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-3.1.1/lib/lamby.rb:25:in `handler'",
    "/var/task/app.rb:18:in `handler'"
    ]
}
```

**Comment by diidiiman** [comment]
Closing as found the issue resolved in Lamby package ver 3.1.3
